Get http://localhost:5000/api/account
###
Get http://localhost:5000/api/account/detail/620760233673cef815e3b608

###
POST http://localhost:5000/api/account/create
Content-Type: application/json

{
    "username" : "Admin" ,
    "password" : "Admin",
    "email"    : "Admin@gmail.com"
}

###
PUT http://localhost:5000/api/account/edit/6207e491bc9a6d35803e2f77
Content-Type: application/json

{
    "username" : "789" ,
    "password" : "1111",
    "email"    : "eidte999@gmail.com"
}


###
DELETE  http://localhost:5000/api/account/delete/62079ed3e48b0a1cb52704e6



### academic
Get http://localhost:5000/api/academicyear

###
Get http://localhost:5000/api/academicyear/delete/620d1783e5760c16bf408790

###
GET  http://localhost:5000/api/academicyear/

###

POST  http://localhost:5000/api/academicyear/add
Content-Type: application/json

{
    "academicTitle" : "heloo" ,
    "academicDescription" : "hi" 
}

###
###

get http://localhost:5000/api/academicyear/edit/620f874fb98444f349ba0756
Content-Type: application/json

{
    "academicTitle" : "thay huy " ,
    "academicDescription" : "nhung ma bi dep trai" 
}

###

POST    http://localhost:5000/user/profile/edit/62166698a7f49721e47b6abe
Content-Type: application/json

{
    "fullName" : "tuanhuy " ,
    "emails": ["hieudeptrai@yahoo,con"],
    "phones": [ 9846214721],
    "streets": ["huyyyy"],
    "cities": ["dsadsa"],
    "countries": [""]
}

###
POST    http://localhost:5000/admin/department/create
Content-Type: application/json

{
    "name":"the cat",
    "description":"Hieu's cat"
}
###
POST     http://localhost:5000/admin/department/edit/621eecdc7dcf48b252efb840
Content-Type: application/json

{
    "name":"hoang van tuan huy",
    "description":"code code"
}

###
GET http://localhost:5000/setting/setting-password/6224747213141e5782c5452c

Content-Type: application/json


